services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: platform
      POSTGRES_PASSWORD: platform_dev_pwd
      POSTGRES_DB: platform
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  pgdata:
  jenkins_home:
